code: model-gcc
version: 1.0.0
name: 工地车辆检测模型
description: 用于检测渣土车、挖掘机、吊车等工程车辆
author: AI Team
create_time: '2024-12-10T15:57:36.025073'
update_time: '2024-12-10T15:57:36.025082'
path: ''
train: images/train
val: images/val
nc: 3
names:
  0: 渣土车
  1: 挖掘机
  2: 吊车
