version: '3.8'

services:
  yolo-detector:
    image: yolo-detector:latest
    container_name: yolo-detector
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - OPENCV_VIDEOIO_PRIORITY_MSMF=0
      - OPENCV_VIDEOIO_PRIORITY_V4L=100
      - OPENCV_IO_ENABLE_OPENEXR=0
      - DOCKER_ENV=true
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./model:/app/model
      - /etc/resolv.conf:/etc/resolv.conf:ro
    networks:
      - yolo_net
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  yolo_net:
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: yolo_bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16 