services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - ./model:/app/model:ro
      - ./data:/app/data
      - ./results:/app/results
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_BUILDKIT=1
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped