callback:
  enabled: true
  retry:
    max_retries: 10
    retry_delay: 1.0
    timeout: 10
  url: http://127.0.0.1:8081
console:
  enabled: false
  show_details: true
  show_separator: true
  show_time: true
  show_total: true
display:
  show_fps: true
  show_window: true
  window_name: MeekYolo Detection
environment:
  enable_gui: true
  is_docker: false
model:
  conf_thres: 0.5
  path: model/model-gcc/best.pt
model_management:
  model_config_template:
    author: ''
    code: ''
    create_time: ''
    description: ''
    name: ''
    update_time: ''
    version: 1.0.0
  model_dir: model
  required_files:
  - best.pt
  - data.yaml
  temp_dir: temp/models
print:
  enabled: false
source:
  image:
    path: data/test.png
    save_path: results/test_result.png
  images:
    formats:
    - .jpg
    - .jpeg
    - .png
    input_dir: data/images
    save_dir: results/images
  rtsp:
    ffmpeg_options:
    - ?tcp
    url: null
  type: rtsp
  video:
    fps: 30
    path: data/video/test2.mp4
    save_path: results/video/test_result2.mp4
tracking:
  enabled: true
  persist: true
visualization:
  show_anchor: true
  show_box: true
  show_class: true
  show_confidence: true
  show_line: true
  show_position: true
  show_size: true
  show_track_id: true
  style:
    chinese_text_size: 20
    colors:
      background:
      - 0
      - 0
      - 0
      text:
      - 255
      - 255
      - 255
    font_scale: 0.6
    margin: 5
    thickness: 2
zlmediakit:
  enabled: true
  host: http://localhost:8000
  rtsp:
    port: 8554
    tcp_mode: true
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
